In [101]:
import pandas as pd
df = pd.read_csv('Crime_Data.csv')

In [173]:
df.head()

TIME OCC  AREA  AREA NAME  Rpt Dist No  Crm Cd  \
0        21     7   Wilshire          784     510   
1        18     1    Central          182     330   
2        17     3  Southwest          356     480   
3        20     9   Van Nuys          964     343   
4        12     6  Hollywood          666     354   

                                Crm Cd Desc  Vict Age Vict Sex  Premis Cd  \
0                          VEHICLE - STOLEN         0        M        101   
1                     BURGLARY FROM VEHICLE        47        M        128   
2                             BIKE - STOLEN        19        X        502   
3  SHOPLIFTING-GRAND THEFT ($950.01 & OVER)        19        M        405   
4                         THEFT OF IDENTITY        28        M        102   

                                    Premis Desc  ...   Status Desc Crm Cd 1  \
0                                        STREET  ...  Adult Arrest      510   
1             BUS STOP/LAYOVER (ALSO QUERY 124)  ...   Invest Cont      330   
2  MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)  ...   Invest Cont      480   
3                                CLOTHING STORE  ...   Invest Cont      343   
4                                      SIDEWALK  ...   Invest Cont      354   

  Crm Cd 2  Crm Cd 3  Crm Cd 4  R.Year  R.Month  O.Year  O.Month  \
0    998.0       NaN       NaN    2020        3    2020        3   
1    998.0       NaN       NaN    2020        2    2020        2   
2      NaN       NaN       NaN    2020       11    2020       11   
3      NaN       NaN       NaN    2023        5    2020        3   
4      NaN       NaN       NaN    2022        8    2020        8   

   Law-break_Count  
0                2  
1                2  
2                1  
3                1  
4                1  

[5 rows x 22 columns]

In [103]:
df.drop(['DR_NO', 'Part 1-2'], axis=1, inplace=True)


In [105]:
df.drop(['LOCATION', 'LAT','LON'], axis=1, inplace=True)

In [109]:
df.drop(['Mocodes'], axis=1, inplace=True)

In [112]:
df.drop(['Cross Street'], axis=1, inplace=True)

In [118]:
df.drop(['Date Rptd'], axis=1, inplace=True)

In [119]:
df.drop(['DATE OCC'], axis=1, inplace=True)

In [122]:
df.drop(['Vict Descent'], axis=1, inplace=True)

In [142]:
df.drop(['Weapon Desc'], axis=1, inplace=True)

In [149]:
df.drop(['Non-Null Count'], axis=1, inplace=True)

In [172]:
df.describe()

TIME OCC           AREA    Rpt Dist No         Crm Cd  \
count  982041.000000  982041.000000  982041.000000  982041.000000   
mean       13.213087      10.699875    1116.420529     500.903619   
std         6.513768       6.108293     610.943170     206.201111   
min         0.000000       1.000000     101.000000     110.000000   
25%         9.000000       5.000000     587.000000     331.000000   
50%        14.000000      11.000000    1141.000000     442.000000   
75%        19.000000      16.000000    1617.000000     626.000000   
max        23.000000      21.000000    2199.000000     956.000000   

            Vict Age      Premis Cd  Weapon Used Cd       Crm Cd 1  \
count  982041.000000  982041.000000   982041.000000  982041.000000   
mean       29.089033     306.073803      120.786738     500.659940   
std        21.968397     219.068177      185.574776     205.999944   
min        -4.000000     101.000000        0.000000     110.000000   
25%         0.000000     101.000000        0.000000     331.000000   
50%        30.000000     203.000000        0.000000     442.000000   
75%        44.000000     501.000000      309.000000     626.000000   
max       120.000000     971.000000      516.000000     956.000000   

           Crm Cd 2     Crm Cd 3   Crm Cd 4         R.Year        R.Month  \
count  68717.000000  2311.000000   64.00000  982041.000000  982041.000000   
mean     958.144695   984.204673  991.21875    2021.862242       6.287203   
std      110.223635    51.485644   27.06985       1.293091       3.430284   
min      210.000000   310.000000  821.00000    2020.000000       1.000000   
25%      998.000000   998.000000  998.00000    2021.000000       3.000000   
50%      998.000000   998.000000  998.00000    2022.000000       6.000000   
75%      998.000000   998.000000  998.00000    2023.000000       9.000000   
max      999.000000   999.000000  999.00000    2024.000000      12.000000   

              O.Year        O.Month  Law-break_Count  
count  982041.000000  982041.000000    982041.000000  
mean     2021.831150       6.278550         1.072392  
std         1.290439       3.438471         0.268549  
min      2020.000000       1.000000         1.000000  
25%      2021.000000       3.000000         1.000000  
50%      2022.000000       6.000000         1.000000  
75%      2023.000000       9.000000         1.000000  
max      2024.000000      12.000000         4.000000

In [150]:
df.isnull().sum()

TIME OCC                0
AREA                    0
AREA NAME               0
Rpt Dist No             0
Crm Cd                  0
Crm Cd Desc             0
Vict Age                0
Vict Sex           138430
Premis Cd               0
Premis Desc             0
Weapon Used Cd          0
Status                  0
Status Desc             0
Crm Cd 1                0
Crm Cd 2           913324
Crm Cd 3           979730
Crm Cd 4           981977
R.Year                  0
R.Month                 0
O.Year                  0
O.Month                 0
Law-break_Count         0
dtype: int64

In [115]:
df['Date Rptd'] = pd.to_datetime(df['Date Rptd'], format='%m/%d/%Y %I:%M:%S %p')

# Extract only the year
df['R.Year'] = df['Date Rptd'].dt.year

# Extract only the month
df['R.Month'] = df['Date Rptd'].dt.month

df['DATE OCC'] = pd.to_datetime(df['DATE OCC'], format='%m/%d/%Y %I:%M:%S %p')

# Extract only the year
df['O.Year'] = df['DATE OCC'].dt.year

# Extract only the month
df['O.Month'] = df['DATE OCC'].dt.month

In [174]:
df['Crm Cd Desc'].unique()

array(['VEHICLE - STOLEN', 'BURGLARY FROM VEHICLE', 'BIKE - STOLEN',
       'SHOPLIFTING-GRAND THEFT ($950.01 & OVER)', 'THEFT OF IDENTITY',
       'BATTERY - SIMPLE ASSAULT',
       'SODOMY/SEXUAL CONTACT B/W PENIS OF ONE PERS TO ANUS OTH',
       'CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 YRS OLDER)',
       'ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT',
       'LETTERS, LEWD  -  TELEPHONE CALLS, LEWD',
       'THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LIVESTK,PROD',
       'CRIMINAL THREATS - NO WEAPON DISPLAYED',
       'EMBEZZLEMENT, GRAND THEFT ($950.01 & OVER)',
       'THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)',
       'CHILD ANNOYING (17YRS & UNDER)',
       'THEFT PLAIN - PETTY ($950 & UNDER)',
       'INTIMATE PARTNER - SIMPLE ASSAULT', 'LEWD CONDUCT',
       'THEFT PLAIN - ATTEMPT', 'BURGLARY',
       'THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND OVER)', 'ROBBERY',
       'BUNCO, GRAND THEFT', 'BATTERY WITH SEXUAL CONTACT',
       'INTIMATE PARTNER - AGGRAVA

In [153]:
df['Weapon Used Cd'].unique()

array([  0, 400, 307, 500, 511, 301, 102, 106, 200, 305, 205, 215, 223,
       512, 308, 207, 515, 201, 311, 114, 109, 113, 208, 107, 204, 312,
       306, 103, 218, 506, 101, 212, 216, 206, 303, 304, 302, 309, 513,
       213, 210, 219, 104, 310, 503, 110, 510, 514, 202, 221, 211, 112,
       501, 105, 508, 504, 203, 115, 509, 122, 505, 217, 120, 220, 502,
       507, 516, 300, 214, 125, 108, 116, 121, 209, 123, 111, 118, 119,
       117, 124])

In [168]:
df['Crm Cd 2'].unique()

array([998.,  nan, 821., 860., 820., 813., 812., 815., 814., 946., 230.,
       510., 994., 624., 930., 740., 761., 522., 649., 480., 626., 900.,
       434., 745., 521., 648., 520., 910., 901., 999., 664., 933., 440.,
       990., 980., 888., 341., 420., 920., 236., 445., 625., 251., 943.,
       350., 654., 997., 668., 250., 310., 627., 220., 433., 343., 956.,
       940., 921., 330., 996., 753., 647., 850., 903., 210., 442., 928.,
       886., 451., 670., 666., 942., 653., 410., 660., 473., 441., 951.,
       623., 763., 830., 810., 662., 762., 949., 906., 979., 760., 474.,
       950., 354., 944., 993., 972., 431., 890., 331., 471., 902., 932.,
       430., 931., 822., 231., 661., 978., 922., 954., 976., 651., 486.,
       948., 352., 421., 320., 945., 755., 351., 345., 235., 437., 865.,
       924., 485., 450., 470., 438., 846.])

In [138]:
df['Weapon Used Cd'] = df['Weapon Used Cd'].fillna(0).astype(int)

In [128]:
df = df[df['Vict Sex'].str.strip() != '-']

In [127]:
df['TIME OCC'] = df['TIME OCC'] / 100
df['TIME OCC'] = df['TIME OCC'].astype(int)

In [132]:
df = df.dropna(subset=['Premis Desc'])

In [134]:
df = df.dropna(subset=['Crm Cd 1'])

In [146]:
df['Law-break_Count'] = df[['Crm Cd 1', 'Crm Cd 2', 'Crm Cd 3', 'Crm Cd 4']].notnull().sum(axis=1)

In [147]:
df['Law-break_Count'].unique()

array([2, 1, 3, 4], dtype=int64)

In [151]:
df.head()

TIME OCC  AREA  AREA NAME  Rpt Dist No  Crm Cd  \
0        21     7   Wilshire          784     510   
1        18     1    Central          182     330   
2        17     3  Southwest          356     480   
3        20     9   Van Nuys          964     343   
4        12     6  Hollywood          666     354   

                                Crm Cd Desc  Vict Age Vict Sex  Premis Cd  \
0                          VEHICLE - STOLEN         0        M      101.0   
1                     BURGLARY FROM VEHICLE        47        M      128.0   
2                             BIKE - STOLEN        19        X      502.0   
3  SHOPLIFTING-GRAND THEFT ($950.01 & OVER)        19        M      405.0   
4                         THEFT OF IDENTITY        28        M      102.0   

                                    Premis Desc  ...   Status Desc Crm Cd 1  \
0                                        STREET  ...  Adult Arrest    510.0   
1             BUS STOP/LAYOVER (ALSO QUERY 124)  ...   Invest Cont    330.0   
2  MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)  ...   Invest Cont    480.0   
3                                CLOTHING STORE  ...   Invest Cont    343.0   
4                                      SIDEWALK  ...   Invest Cont    354.0   

  Crm Cd 2  Crm Cd 3  Crm Cd 4  R.Year  R.Month  O.Year  O.Month  \
0    998.0       NaN       NaN    2020        3    2020        3   
1    998.0       NaN       NaN    2020        2    2020        2   
2      NaN       NaN       NaN    2020       11    2020       11   
3      NaN       NaN       NaN    2023        5    2020        3   
4      NaN       NaN       NaN    2022        8    2020        8   

   Law-break_Count  
0                2  
1                2  
2                1  
3                1  
4                1  

[5 rows x 22 columns]

In [152]:
df.describe()

TIME OCC           AREA    Rpt Dist No         Crm Cd  \
count  982041.000000  982041.000000  982041.000000  982041.000000   
mean       13.213087      10.699875    1116.420529     500.903619   
std         6.513768       6.108293     610.943170     206.201111   
min         0.000000       1.000000     101.000000     110.000000   
25%         9.000000       5.000000     587.000000     331.000000   
50%        14.000000      11.000000    1141.000000     442.000000   
75%        19.000000      16.000000    1617.000000     626.000000   
max        23.000000      21.000000    2199.000000     956.000000   

            Vict Age      Premis Cd  Weapon Used Cd       Crm Cd 1  \
count  982041.000000  982041.000000   982041.000000  982041.000000   
mean       29.089033     306.073803      120.786738     500.659940   
std        21.968397     219.068177      185.574776     205.999944   
min        -4.000000     101.000000        0.000000     110.000000   
25%         0.000000     101.000000        0.000000     331.000000   
50%        30.000000     203.000000        0.000000     442.000000   
75%        44.000000     501.000000      309.000000     626.000000   
max       120.000000     971.000000      516.000000     956.000000   

           Crm Cd 2     Crm Cd 3   Crm Cd 4         R.Year        R.Month  \
count  68717.000000  2311.000000   64.00000  982041.000000  982041.000000   
mean     958.144695   984.204673  991.21875    2021.862242       6.287203   
std      110.223635    51.485644   27.06985       1.293091       3.430284   
min      210.000000   310.000000  821.00000    2020.000000       1.000000   
25%      998.000000   998.000000  998.00000    2021.000000       3.000000   
50%      998.000000   998.000000  998.00000    2022.000000       6.000000   
75%      998.000000   998.000000  998.00000    2023.000000       9.000000   
max      999.000000   999.000000  999.00000    2024.000000      12.000000   

              O.Year        O.Month  Law-break_Count  
count  982041.000000  982041.000000    982041.000000  
mean     2021.831150       6.278550         1.072392  
std         1.290439       3.438471         0.268549  
min      2020.000000       1.000000         1.000000  
25%      2021.000000       3.000000         1.000000  
50%      2022.000000       6.000000         1.000000  
75%      2023.000000       9.000000         1.000000  
max      2024.000000      12.000000         4.000000

In [154]:
df['TIME OCC'] = df['TIME OCC'].fillna(0).astype(int)

In [155]:
df['AREA'] = df['AREA'].fillna(0).astype(int)

In [159]:
df['Premis Cd'] = df['Premis Cd'].fillna(0).astype(int)

In [160]:
df['Weapon Used Cd'] = df['Weapon Used Cd'].fillna(0).astype(int)

In [161]:
df['Crm Cd 1'] = df['Crm Cd 1'].fillna(0).astype(int)

In [162]:
df['Crm Cd 2'] = df['Crm Cd 2'].fillna(0).astype(int)

In [163]:
df['Crm Cd 3'] = df['Crm Cd 3'].fillna(0).astype(int)

In [164]:
df['Crm Cd 4'] = df['Crm Cd 4'].fillna(0).astype(int)

In [157]:
df['Crm Cd'] = df['Crm Cd'].fillna(0).astype(int)

In [158]:
df['Vict Age'] = df['Vict Age'].fillna(0).astype(int)

In [156]:
df['Rpt Dist No'] = df['Rpt Dist No'].fillna(0).astype(int)

In [167]:
import numpy as np
df[['Crm Cd 1', 'Crm Cd 2', 'Crm Cd 3', 'Crm Cd 4']] = df[['Crm Cd 1', 'Crm Cd 2', 'Crm Cd 3', 'Crm Cd 4']].replace(0, np.nan)

In [169]:
df.to_csv('Crime_Data.cleaned.csv', index=False) 

In [171]:
df['Rpt Dist No'].unique()

array([ 784,  182,  356, ..., 1100,  672,  709])